"""Demo catalog for seed.py. Prices in dollars; images live in frontend/public/products/."""

STORES = {
    "apex": {
        "email": "official@apex.demo",
        "owner": "Riley Morgan",
        "store_name": "Apex Official Store",
        "description": "Laptops, monitors, storage and everyday tech, shipped fast from Apex fulfillment centers.",
    },
    "northwind": {
        "email": "northwind@apex.demo",
        "owner": "Maya Chen",
        "store_name": "Northwind Audio",
        "description": "Independent audio shop: headphones, speakers and turntables tuned by people who listen.",
    },
    "keyforge": {
        "email": "seller@apex.demo",
        "owner": "Alex Rivera",
        "store_name": "KeyForge Supply",
        "description": "Mechanical keyboards, mice and desk gear for people who type all day.",
    },
}

# slug, name, parent, icon, position
CATEGORIES = [
    ("electronics", "Electronics", None, None, 0),
    ("computing", "Computing", None, None, 0),
    ("home-kitchen", "Home & Kitchen", None, None, 0),
    ("accessories", "Accessories", None, "cable", 7),
    ("audio", "Audio & Headphones", "electronics", "headphones", 1),
    ("smart-home", "Smart Home", "electronics", "house", 5),
    ("wearables", "Wearables", "electronics", "watch", 8),
    ("laptops", "Laptops", "computing", "laptop", 2),
    ("keyboards", "Keyboards", "computing", "keyboard", 3),
    ("monitors", "Monitors", "computing", "monitor", 4),
    ("mice", "Mice", "computing", None, 0),
    ("storage", "Storage", "computing", None, 0),
    ("kitchen", "Kitchen", "home-kitchen", "coffee", 6),
]

BLACK, SILVER, NAVY, SAND, WHITE = "#1f2328", "#cfd3d8", "#1e2a44", "#d8c3a5", "#f3f4f6"

PRODUCTS = [
    # ------------------------------------------------------------------ audio
    dict(
        slug="sonora-soundmaster-pro-anc-headphones",
        store="northwind",
        brand="Sonora",
        cat="audio",
        title="Sonora SoundMaster Pro Hybrid Active Noise Cancelling Headphones",
        price=199.99,
        list=279.99,
        rating=4.8,
        count=18492,
        bought=2140,
        stock=9,
        featured=True,
        badges=["Apex Choice", "Best Seller"],
        speed="one_day",
        images=3,
        desc="Spatial audio with dynamic head tracking, multipoint Bluetooth 5.4, 60-hour battery and "
        "ultra-comfort memory foam.",
        hl=[
            "Custom 40mm titanium drivers with deep, controlled bass down to 8Hz",
            "-45dB adaptive ANC samples ambient noise 380,000 times per second",
            "5-minute USB-C charge gives 4 hours of playback",
            "Pressure-relieving memory foam in breathable vegan leather",
        ],
        specs={
            "Wireless protocol": "Bluetooth 5.4 LE Audio",
            "Supported codecs": "LDAC, AAC, SBC, aptX Adaptive",
            "Battery life": "60 hours (ANC off), 40 hours (ANC on)",
            "Weight": "254 g (8.95 oz)",
            "Multipoint pairing": "Yes, up to 3 devices",
        },
        facets={"audio_type": "Over-ear", "connectivity": "Wireless"},
        colors=[
            ("Matte Obsidian", BLACK, 0, 9),
            ("Silver Mist", SILVER, 0, 14),
            ("Midnight Navy", NAVY, 0, 6),
            ("Desert Sand", SAND, 0, 3),
        ],
        editions=[
            ("Standard Edition", "Headphones, 3.5mm cable, braided USB-C fast cable", 0),
            ("Traveler Bundle", "+ Premium hard shell travel case and flight adapter", 30),
        ],
    ),
    dict(
        slug="northwind-studio-50-reference-headphones",
        store="northwind",
        brand="Northwind",
        cat="audio",
        title="Northwind Studio 50 Pro Reference Monitoring Headphones",
        price=118.99,
        list=169.99,
        rating=4.6,
        count=3204,
        bought=860,
        stock=42,
        featured=True,
        badges=["Limited Deal"],
        speed="one_day",
        images=3,
        deal=(30, 5, 160, 61),
        desc="Closed-back studio headphones with a flat, honest response for mixing, editing and long listening.",
        hl=[
            "50mm drivers tuned flat for accurate mixing",
            "Detachable coiled and straight cables included",
            "Swivelling ear cups for one-ear monitoring",
        ],
        specs={
            "Type": "Closed-back, over-ear",
            "Impedance": "38 ohms",
            "Frequency response": "5 Hz - 40 kHz",
            "Cable": "Detachable 3m coiled + 1.2m straight",
            "Weight": "285 g",
        },
        facets={"audio_type": "Over-ear", "connectivity": "Wired"},
    ),
    dict(
        slug="apex-basics-wired-studio-headphones",
        store="apex",
        brand="Apex Basics",
        cat="audio",
        title="Apex Basics Wired Over-Ear Headphones with Inline Mic",
        price=24.99,
        list=None,
        rating=4.3,
        count=6120,
        bought=1420,
        stock=180,
        badges=[],
        speed="one_day",
        images=2,
        desc="Lightweight everyday headphones with a tangle-free cable and an inline microphone for calls.",
        hl=[
            "Soft cushioned ear cups for all-day comfort",
            "Inline mic and play/pause button",
            "Folds flat for travel",
        ],
        specs={"Connection": "3.5mm jack", "Cable length": "1.5 m", "Weight": "190 g"},
        facets={"audio_type": "Over-ear", "connectivity": "Wired"},
        colors=[("Black", BLACK, 0, 120), ("Sunshine Yellow", "#f5c518", 0, 60)],
    ),
    dict(
        slug="sonora-halo-lite-wireless-headphones",
        store="northwind",
        brand="Sonora",
        cat="audio",
        title="Sonora Halo Lite Wireless On-Ear Headphones, 50-Hour Battery",
        price=79.99,
        list=99.99,
        rating=4.4,
        count=2311,
        bought=540,
        stock=65,
        badges=["New Arrival"],
        speed="two_day",
        images=2,
        desc="Feather-light on-ear headphones with a warm sound, quick pairing and a battery that lasts all week.",
        hl=["50 hours of playback on one charge", "Weighs just 158 g", "Fast pair with Android and iOS"],
        specs={"Wireless protocol": "Bluetooth 5.3", "Battery life": "50 hours", "Weight": "158 g"},
        facets={"audio_type": "On-ear", "connectivity": "Wireless"},
        colors=[("Cloud White", WHITE, 0, 40), ("Blush", "#e9c9c9", 0, 25)],
    ),
    dict(
        slug="sonora-pulse-wireless-earbuds",
        store="northwind",
        brand="Sonora",
        cat="audio",
        title="Sonora Pulse True Wireless Earbuds with ANC and Wireless Charging Case",
        price=89.99,
        list=129.99,
        rating=4.5,
        count=9875,
        bought=1980,
        stock=120,
        featured=True,
        badges=["Best Seller"],
        speed="one_day",
        images=2,
        desc="Compact noise-cancelling earbuds with a pocketable wireless charging case and IPX5 sweat resistance.",
        hl=[
            "Adaptive ANC with transparency mode",
            "8 hours per charge, 32 with the case",
            "IPX5 sweat and splash resistant",
        ],
        specs={"Wireless protocol": "Bluetooth 5.3", "Battery": "8h + 24h case", "Water resistance": "IPX5"},
        facets={"audio_type": "In-ear", "connectivity": "Wireless"},
    ),
    dict(
        slug="northwind-open-ear-sport-earbuds",
        store="northwind",
        brand="Northwind",
        cat="audio",
        title="Northwind Open-Ear Sport Earbuds with Secure Ear Hooks",
        price=69.99,
        list=None,
        rating=4.2,
        count=1430,
        bought=310,
        stock=58,
        badges=[],
        speed="two_day",
        images=2,
        desc="Open-ear design keeps you aware of traffic while you run, with hooks that stay put.",
        hl=[
            "Open-ear design for situational awareness",
            "IP55 dust and water resistance",
            "10 hours of playback",
        ],
        specs={"Wireless protocol": "Bluetooth 5.3", "Battery": "10 hours", "Water resistance": "IP55"},
        facets={"audio_type": "In-ear", "connectivity": "Wireless"},
    ),
    dict(
        slug="northwind-boom-cube-bluetooth-speaker",
        store="northwind",
        brand="Northwind",
        cat="audio",
        title="Northwind Boom Cube Portable Bluetooth Speaker, Waterproof",
        price=59.99,
        list=79.99,
        rating=4.6,
        count=4280,
        bought=760,
        stock=90,
        badges=["Top Rated"],
        speed="one_day",
        images=2,
        desc="A small speaker with surprisingly big sound, a leather carry strap and 16 hours of battery.",
        hl=[
            "360-degree sound with passive bass radiator",
            "IP67 waterproof and dustproof",
            "Pair two for stereo",
        ],
        specs={"Output": "20 W", "Battery": "16 hours", "Water resistance": "IP67", "Weight": "540 g"},
        colors=[("Chalk White", WHITE, 0, 50), ("Graphite", BLACK, 0, 40)],
    ),
    dict(
        slug="sonora-arc-31-soundbar",
        store="northwind",
        brand="Sonora",
        cat="audio",
        title="Sonora Arc 3.1 Channel Soundbar with Wireless Subwoofer",
        price=249.00,
        list=329.00,
        rating=4.5,
        count=2045,
        bought=280,
        stock=24,
        badges=[],
        speed="two_day",
        images=2,
        desc="Clear dialogue and cinematic bass for TVs 40 inches and up, with HDMI eARC and one-remote control.",
        hl=[
            "Dedicated center channel for crisp dialogue",
            "Wireless subwoofer for deep bass",
            "HDMI eARC, optical and Bluetooth inputs",
        ],
        specs={"Channels": "3.1", "Total power": "380 W", "Inputs": "HDMI eARC, optical, Bluetooth 5.0"},
    ),
    dict(
        slug="northwind-heritage-bluetooth-turntable",
        store="northwind",
        brand="Northwind",
        cat="audio",
        title="Northwind Heritage Belt-Drive Turntable with Bluetooth Output",
        price=149.00,
        list=189.00,
        rating=4.4,
        count=870,
        bought=95,
        stock=2,
        badges=[],
        speed="standard",
        images=2,
        desc="A warm, walnut-finished turntable that plays to your speakers or streams to Bluetooth headphones.",
        hl=["Belt drive with 33 and 45 RPM", "Built-in switchable phono preamp", "Bluetooth out to speakers"],
        specs={"Speeds": "33 1/3, 45 RPM", "Drive": "Belt", "Output": "RCA line/phono, Bluetooth"},
    ),
    # ---------------------------------------------------------------- laptops
    dict(
        slug="apex-zenith-ultra-14-laptop",
        store="apex",
        brand="Apex",
        cat="laptops",
        title="Apex Zenith Ultra 14 Laptop, Core Ultra 7, 32GB RAM, 1TB SSD",
        price=1199.00,
        list=1399.00,
        rating=4.9,
        count=1260,
        bought=410,
        stock=35,
        featured=True,
        badges=["Best Seller"],
        speed="one_day",
        images=3,
        desc="A 1.2 kg aluminum laptop with a 14-inch 2.8K OLED display and all-day battery life.",
        hl=[
            "14-inch 2.8K OLED, 120Hz, 100% DCI-P3",
            "Up to 18 hours of battery life",
            "Two Thunderbolt 4 ports and HDMI 2.1",
        ],
        specs={
            "Processor": "Intel Core Ultra 7 155H",
            "Memory": "32GB LPDDR5X",
            "Storage": "1TB PCIe 4.0 SSD",
            "Display": '14" 2880x1800 OLED',
            "Weight": "1.2 kg",
        },
        facets={"memory": "32GB"},
        editions=[
            ("32GB / 1TB", "Core Ultra 7, 32GB RAM, 1TB SSD", 0),
            ("32GB / 2TB", "Core Ultra 7, 32GB RAM, 2TB SSD", 180),
        ],
    ),
    dict(
        slug="apex-airbook-13-laptop",
        store="apex",
        brand="Apex",
        cat="laptops",
        title="Apex AirBook 13 Lightweight Laptop, 16GB RAM, 512GB SSD",
        price=849.00,
        list=949.00,
        rating=4.6,
        count=2210,
        bought=530,
        stock=48,
        badges=["Apex Choice"],
        speed="one_day",
        images=2,
        desc="Fanless, silent and under a kilogram, with a sharp 13-inch display for work on the go.",
        hl=["Fanless design, completely silent", "13.3-inch 2.5K IPS display", "15 hours of battery life"],
        specs={"Processor": "Apex A3 8-core", "Memory": "16GB", "Storage": "512GB SSD", "Weight": "0.98 kg"},
        facets={"memory": "16GB"},
        colors=[("Silver", SILVER, 0, 30), ("Space Gray", "#4b5563", 0, 18)],
    ),
    dict(
        slug="halcyon-creator-16-oled-laptop",
        store="apex",
        brand="Halcyon",
        cat="laptops",
        title="Halcyon Creator 16 OLED Laptop, RTX 4060, 32GB RAM, 1TB SSD",
        price=1649.00,
        list=1899.00,
        rating=4.7,
        count=640,
        bought=120,
        stock=4,
        badges=[],
        speed="two_day",
        images=2,
        desc="A 16-inch creator laptop with a calibrated OLED panel and a GPU for editing and 3D work.",
        hl=[
            "16-inch 3.2K OLED, factory calibrated",
            "NVIDIA GeForce RTX 4060 8GB",
            "Full-size SD card reader",
        ],
        specs={
            "Processor": "Intel Core i9-13900H",
            "Graphics": "RTX 4060 8GB",
            "Memory": "32GB DDR5",
            "Storage": "1TB SSD",
        },
        facets={"memory": "32GB"},
    ),
    dict(
        slug="halcyon-chromebook-plus-14",
        store="apex",
        brand="Halcyon",
        cat="laptops",
        title="Halcyon Chromebook Plus 14, 8GB RAM, 256GB Storage",
        price=399.00,
        list=449.00,
        rating=4.3,
        count=1880,
        bought=360,
        stock=70,
        badges=[],
        speed="one_day",
        images=2,
        desc="A fast, simple Chromebook with a full HD touch screen, ideal for school and browsing.",
        hl=["14-inch Full HD touch display", "10 hours of battery life", "Automatic updates for 10 years"],
        specs={"Processor": "Intel Core i3", "Memory": "8GB", "Storage": "256GB", "Weight": "1.4 kg"},
        facets={"memory": "8GB"},
    ),
    # -------------------------------------------------------------- keyboards
    dict(
        slug="keyforge-horizon-75-tri-mode-keyboard",
        store="keyforge",
        brand="KeyForge",
        cat="keyboards",
        title="KeyForge Horizon 75 Tri-Mode Wireless Mechanical Keyboard, Gasket Mount",
        price=119.99,
        list=149.99,
        rating=4.8,
        count=3410,
        bought=1240,
        stock=64,
        featured=True,
        badges=["Best Seller"],
        speed="one_day",
        images=3,
        desc="Gasket-mounted 75% board with pre-lubed linear switches, hot-swap sockets and a volume knob.",
        hl=[
            "Tri-mode: 2.4GHz, Bluetooth 5.1 and USB-C",
            "Hot-swappable 3- and 5-pin sockets",
            "Five layers of sound dampening foam",
            "4000mAh battery, up to 200 hours with lights off",
        ],
        specs={
            "Layout": "75%, 81 keys",
            "Switches": "KeyForge Linear Red, pre-lubed",
            "Mount": "Gasket",
            "Connectivity": "2.4GHz, Bluetooth 5.1, USB-C",
            "Battery": "4000 mAh",
        },
        facets={
            "switch_type": "Linear",
            "connectivity": "Tri-Mode",
            "form_factor": "75%",
            "hot_swap": "Hot-swappable",
        },
        colors=[("Carbon Black", BLACK, 0, 40), ("Frost White", WHITE, 0, 24)],
        editions=[("Linear Red", "Smooth linear, 45g", 0), ("Tactile Brown", "Light tactile bump, 55g", 0)],
    ),
    dict(
        slug="keyforge-studio-lite-65-keyboard",
        store="keyforge",
        brand="KeyForge",
        cat="keyboards",
        title="KeyForge Studio Lite 65% Compact Bluetooth Mechanical Keyboard",
        price=69.99,
        list=89.99,
        rating=4.5,
        count=950,
        bought=480,
        stock=75,
        featured=True,
        badges=["Limited Deal"],
        speed="one_day",
        images=2,
        deal=(22, 9, 120, 26),
        desc="A compact 65% board that keeps the arrow keys, pairs with three devices and fits in any bag.",
        hl=["65% layout with dedicated arrows", "Pairs with up to three devices", "PBT double-shot keycaps"],
        specs={"Layout": "65%, 68 keys", "Switches": "Linear Yellow", "Connectivity": "Bluetooth 5.1, USB-C"},
        facets={
            "switch_type": "Linear",
            "connectivity": "Bluetooth",
            "form_factor": "65%",
            "hot_swap": "Hot-swappable",
        },
    ),
    dict(
        slug="keyforge-retro-97-smart-display-keyboard",
        store="keyforge",
        brand="KeyForge",
        cat="keyboards",
        title="KeyForge Retro 97 Mechanical Keyboard with Smart Display",
        price=105.99,
        list=None,
        rating=4.7,
        count=1840,
        bought=390,
        stock=33,
        badges=["New Arrival"],
        speed="one_day",
        images=2,
        desc="Round retro keycaps, a 96% layout with a numpad and a small display for time, battery and mode.",
        hl=[
            "Built-in 0.85-inch smart display",
            "96% layout keeps the numpad",
            "Round typewriter-style keycaps",
        ],
        specs={
            "Layout": "96%, 100 keys",
            "Switches": "Tactile Brown",
            "Connectivity": "2.4GHz, Bluetooth, USB-C",
        },
        facets={
            "switch_type": "Tactile",
            "connectivity": "Tri-Mode",
            "form_factor": "Full Size",
            "hot_swap": "Fixed",
        },
    ),
    dict(
        slug="lumen-k70-mini-60-rgb-keyboard",
        store="keyforge",
        brand="Lumen",
        cat="keyboards",
        title="Lumen K70 Pro Mini Wireless 60% RGB Mechanical Gaming Keyboard",
        price=129.99,
        list=None,
        rating=4.4,
        count=1620,
        bought=300,
        stock=27,
        badges=[],
        speed="one_day",
        images=2,
        desc="A 60% gaming keyboard with per-key RGB, 1000Hz wireless and swappable switches.",
        hl=["Sub-1ms 2.4GHz wireless", "Per-key RGB with onboard profiles", "Hot-swappable switches"],
        specs={"Layout": "60%, 61 keys", "Switches": "Linear Red", "Polling rate": "1000 Hz"},
        facets={
            "switch_type": "Linear",
            "connectivity": "2.4GHz",
            "form_factor": "60%",
            "hot_swap": "Hot-swappable",
        },
    ),
    dict(
        slug="keyforge-tkl-pro-gasket-keyboard",
        store="keyforge",
        brand="KeyForge",
        cat="keyboards",
        title="KeyForge TKL Pro Gasket Mount Wired Mechanical Keyboard",
        price=139.99,
        list=159.99,
        rating=4.7,
        count=720,
        bought=150,
        stock=3,
        badges=["Top Rated"],
        speed="two_day",
        images=2,
        desc="A tenkeyless enthusiast board with an aluminum case, tactile switches and a deep, quiet sound.",
        hl=["CNC aluminum case", "Tactile switches with a crisp bump", "Detachable USB-C cable"],
        specs={"Layout": "TKL, 87 keys", "Switches": "Tactile Brown", "Case": "Aluminum"},
        facets={
            "switch_type": "Tactile",
            "connectivity": "Wired",
            "form_factor": "TKL",
            "hot_swap": "Hot-swappable",
        },
    ),
    dict(
        slug="lumen-mx-mechanical-wireless-keyboard",
        store="keyforge",
        brand="Lumen",
        cat="keyboards",
        title="Lumen MX Mechanical Wireless Illuminated Keyboard, Tactile Quiet",
        price=149.99,
        list=169.99,
        rating=4.6,
        count=8940,
        bought=1100,
        stock=88,
        badges=["Apex Choice"],
        speed="two_day",
        images=2,
        desc="A full-size wireless keyboard for productivity, with smart backlighting and quiet tactile switches.",
        hl=[
            "Full-size layout with numpad",
            "Smart backlighting adjusts to the room",
            "Works with three devices",
        ],
        specs={
            "Layout": "Full size, 108 keys",
            "Switches": "Tactile Quiet",
            "Battery": "Up to 15 days with lighting",
        },
        facets={
            "switch_type": "Tactile",
            "connectivity": "Bluetooth",
            "form_factor": "Full Size",
            "hot_swap": "Fixed",
        },
    ),
    dict(
        slug="apex-basics-full-size-mechanical-keyboard",
        store="apex",
        brand="Apex Basics",
        cat="keyboards",
        title="Apex Basics Wired Mechanical Keyboard, Blue Switches, Full Size",
        price=39.99,
        list=None,
        rating=4.2,
        count=4120,
        bought=820,
        stock=140,
        badges=[],
        speed="one_day",
        images=2,
        desc="An affordable full-size mechanical keyboard with clicky blue switches and blue backlighting.",
        hl=["Clicky blue switches", "Blue LED backlight", "Spill-resistant design"],
        specs={"Layout": "Full size, 104 keys", "Switches": "Clicky Blue", "Connection": "USB-A"},
        facets={
            "switch_type": "Clicky",
            "connectivity": "Wired",
            "form_factor": "Full Size",
            "hot_swap": "Fixed",
        },
    ),
    dict(
        slug="keyforge-slim-75-low-profile-keyboard",
        store="keyforge",
        brand="KeyForge",
        cat="keyboards",
        title="KeyForge Slim 75 Low-Profile Tri-Mode Mechanical Keyboard",
        price=99.99,
        list=119.99,
        rating=4.5,
        count=610,
        bought=170,
        stock=46,
        badges=[],
        speed="one_day",
        images=2,
        desc="Low-profile switches and a 75% layout in a case just 22mm thick, for laptop-like typing.",
        hl=["22mm thin aluminum case", "Low-profile tactile switches", "Tri-mode connection"],
        specs={"Layout": "75%, 84 keys", "Switches": "Low-profile Tactile", "Thickness": "22 mm"},
        facets={
            "switch_type": "Tactile",
            "connectivity": "Tri-Mode",
            "form_factor": "75%",
            "hot_swap": "Fixed",
        },
    ),
    dict(
        slug="keyforge-typewriter-retro-wireless-keyboard",
        store="keyforge",
        brand="KeyForge",
        cat="keyboards",
        title="KeyForge Typewriter Retro Wireless Keyboard, Rose Gold",
        price=59.99,
        list=74.99,
        rating=4.3,
        count=2290,
        bought=260,
        stock=38,
        badges=[],
        speed="two_day",
        images=2,
        desc="A typewriter-inspired wireless keyboard with round keycaps and a satisfying click.",
        hl=["Round typewriter keycaps", "Bluetooth and USB-C", "Rose gold aluminum plate"],
        specs={"Layout": "Full size", "Switches": "Clicky Blue", "Connectivity": "Bluetooth, USB-C"},
        facets={
            "switch_type": "Clicky",
            "connectivity": "Bluetooth",
            "form_factor": "Full Size",
            "hot_swap": "Fixed",
        },
    ),
    # ------------------------------------------------------------------- mice
    dict(
        slug="lumen-verve-ergonomic-vertical-mouse",
        store="keyforge",
        brand="Lumen",
        cat="mice",
        title="Lumen Verve Ergonomic Multi-Device Bluetooth Mouse",
        price=59.99,
        list=79.99,
        rating=4.7,
        count=4990,
        bought=920,
        stock=110,
        badges=["Apex Choice"],
        speed="one_day",
        images=2,
        desc="A sculpted ergonomic mouse with a thumb rest, quiet clicks and a scroll wheel that flies.",
        hl=["Sculpted shape supports your hand", "MagSpeed-style scroll wheel", "Pair up to three devices"],
        specs={
            "Sensor": "8000 DPI",
            "Battery": "70 days on a full charge",
            "Connection": "Bluetooth, USB receiver",
        },
    ),
    dict(
        slug="keyforge-glide-pro-wireless-gaming-mouse",
        store="keyforge",
        brand="KeyForge",
        cat="mice",
        title="KeyForge Glide Pro Ultralight Wireless Gaming Mouse, 58g",
        price=79.99,
        list=None,
        rating=4.6,
        count=1310,
        bought=330,
        stock=52,
        badges=[],
        speed="one_day",
        images=2,
        desc="A 58-gram wireless gaming mouse with a 26K DPI sensor and PTFE feet.",
        hl=["58 g ultralight shell", "26,000 DPI optical sensor", "90 hours of battery"],
        specs={"Weight": "58 g", "Sensor": "26K DPI optical", "Polling rate": "1000 Hz"},
    ),
    dict(
        slug="apex-basics-silent-wireless-mouse",
        store="apex",
        brand="Apex Basics",
        cat="mice",
        title="Apex Basics Silent Wireless Mouse with USB Receiver",
        price=14.99,
        list=None,
        rating=4.4,
        count=12880,
        bought=2900,
        stock=400,
        badges=["Best Seller"],
        speed="one_day",
        images=2,
        desc="Quiet clicks, a comfortable shape and 18 months of battery from one AA cell.",
        hl=["90% quieter clicks", "18-month battery life", "Plug-and-play receiver"],
        specs={"Connection": "2.4GHz USB receiver", "Battery": "1 x AA", "DPI": "1600"},
        colors=[("Cherry Red", "#b91c1c", 0, 200), ("Black", BLACK, 0, 200)],
    ),
    # --------------------------------------------------------------- monitors
    dict(
        slug="apex-visioncraft-27-4k-usb-c-monitor",
        store="apex",
        brand="Apex",
        cat="monitors",
        title='Apex VisionCraft 27" 4K IPS HDR400 USB-C Monitor, 99% sRGB',
        price=349.00,
        list=449.00,
        rating=4.6,
        count=2910,
        bought=380,
        stock=29,
        featured=True,
        badges=["Apex Choice"],
        speed="one_day",
        images=3,
        desc="A color-accurate 27-inch 4K monitor that charges your laptop over a single USB-C cable.",
        hl=["4K UHD IPS panel, 99% sRGB", "USB-C with 90W power delivery", "Height, tilt and pivot stand"],
        specs={"Resolution": "3840 x 2160", "Panel": "IPS, HDR400", "Ports": "USB-C 90W, HDMI 2.0, DP 1.4"},
        facets={"resolution": "4K UHD", "screen_size": "27 in"},
    ),
    dict(
        slug="halcyon-34-ultrawide-curved-monitor",
        store="apex",
        brand="Halcyon",
        cat="monitors",
        title='Halcyon 34" Ultrawide Curved WQHD Monitor, 144Hz',
        price=479.00,
        list=549.00,
        rating=4.5,
        count=1150,
        bought=140,
        stock=17,
        badges=[],
        speed="two_day",
        images=2,
        desc="A 1500R curved ultrawide for immersive games and side-by-side work.",
        hl=["3440x1440 WQHD at 144Hz", "1500R curve", "Built-in KVM switch"],
        specs={"Resolution": "3440 x 1440", "Refresh rate": "144 Hz", "Curvature": "1500R"},
        facets={"resolution": "WQHD", "screen_size": "34 in"},
    ),
    dict(
        slug="apex-basics-24-fhd-monitor",
        store="apex",
        brand="Apex Basics",
        cat="monitors",
        title='Apex Basics 24" Full HD IPS Monitor, 100Hz, Ultra-Thin Bezel',
        price=129.99,
        list=149.99,
        rating=4.4,
        count=5300,
        bought=760,
        stock=95,
        badges=[],
        speed="one_day",
        images=2,
        desc="A sharp, affordable everyday monitor with slim bezels and eye-care settings.",
        hl=["Full HD IPS at 100Hz", "Flicker-free with low blue light", "VESA mount compatible"],
        specs={"Resolution": "1920 x 1080", "Refresh rate": "100 Hz", "Ports": "HDMI, VGA"},
        facets={"resolution": "Full HD", "screen_size": "24 in"},
    ),
    # ---------------------------------------------------------------- storage
    dict(
        slug="apex-drive-pro-2tb-nvme-ssd",
        store="apex",
        brand="Apex",
        cat="storage",
        title="Apex Drive Pro 2TB PCIe Gen 4.0 NVMe SSD, 7,450MB/s",
        price=149.95,
        list=189.99,
        rating=4.9,
        count=8320,
        bought=1300,
        stock=160,
        badges=["Top Rated"],
        speed="one_day",
        images=2,
        desc="A fast M.2 NVMe drive for gaming PCs, workstations and PS5 storage upgrades.",
        hl=["Up to 7,450MB/s reads", "Includes slim heatsink", "5-year limited warranty"],
        specs={"Capacity": "2TB", "Interface": "PCIe Gen 4.0 x4 NVMe", "Form factor": "M.2 2280"},
    ),
    dict(
        slug="strata-portable-ssd-1tb",
        store="apex",
        brand="Strata",
        cat="storage",
        title="Strata Portable SSD 1TB, USB-C, up to 1,050MB/s",
        price=89.99,
        list=109.99,
        rating=4.7,
        count=6700,
        bought=990,
        stock=130,
        badges=[],
        speed="one_day",
        images=2,
        desc="A pocket-size aluminum SSD with fast USB-C transfers and drop resistance up to 2 meters.",
        hl=["Up to 1,050MB/s", "Drop resistant to 2 m", "Works with Mac, PC, iPad and Android"],
        specs={"Capacity": "1TB", "Interface": "USB 3.2 Gen 2", "Weight": "52 g"},
    ),
    dict(
        slug="strata-4tb-external-hard-drive",
        store="apex",
        brand="Strata",
        cat="storage",
        title="Strata 4TB Portable External Hard Drive, USB 3.0",
        price=109.99,
        list=None,
        rating=4.5,
        count=11200,
        bought=740,
        stock=85,
        badges=[],
        speed="two_day",
        images=2,
        desc="Plenty of space for backups, photos and game libraries, in a slim matte case.",
        hl=["4TB of storage", "Automatic backup software", "USB 3.0 and USB 2.0 compatible"],
        specs={"Capacity": "4TB", "Interface": "USB 3.0", "Weight": "230 g"},
    ),
    # ------------------------------------------------------------- smart home
    dict(
        slug="nestly-smart-speaker-mini",
        store="apex",
        brand="Nestly",
        cat="smart-home",
        title="Nestly Smart Speaker Mini (2nd Gen) with Voice Assistant",
        price=49.99,
        list=59.99,
        rating=4.6,
        count=24800,
        bought=3100,
        stock=210,
        badges=["Best Seller"],
        speed="one_day",
        images=2,
        desc="Room-filling sound and a built-in assistant that controls your lights, plugs and thermostat.",
        hl=["360-degree sound", "Works with thousands of smart home devices", "Mic off switch for privacy"],
        specs={"Connectivity": "Wi-Fi 6, Bluetooth 5.0, Thread", "Size": "98 x 84 mm"},
        colors=[("Midnight", BLACK, 0, 120), ("Chalk", WHITE, 0, 90)],
    ),
    dict(
        slug="nestly-smart-thermostat",
        store="apex",
        brand="Nestly",
        cat="smart-home",
        title="Nestly Smart Thermostat with Energy Saving Schedules",
        price=129.00,
        list=149.00,
        rating=4.7,
        count=8600,
        bought=640,
        stock=60,
        featured=True,
        badges=["Apex Choice"],
        speed="one_day",
        images=2,
        desc="A learning thermostat that builds a schedule around you and helps cut heating and cooling bills.",
        hl=["Learns your schedule in a week", "Control from your phone", "Energy history reports"],
        specs={
            "Compatibility": "Most 24V systems",
            "Display": "Round color display",
            "Connectivity": "Wi-Fi",
        },
    ),
    dict(
        slug="orbit-sentryguard-2k-camera-2-pack",
        store="apex",
        brand="Orbit",
        cat="smart-home",
        title="Orbit SentryGuard 2K Smart Home Security Camera (2-Pack)",
        price=49.99,
        list=86.00,
        rating=4.4,
        count=7700,
        bought=1400,
        stock=140,
        badges=["Limited Deal"],
        speed="one_day",
        images=2,
        deal=(42, 3, 200, 182),
        desc="Pan-and-tilt indoor cameras with 2K video, night vision and person detection.",
        hl=["2K video with 360-degree pan", "Person and pet detection", "Local microSD or cloud storage"],
        specs={"Resolution": "2K (2304 x 1296)", "Field of view": "360 pan, 114 tilt", "Pack": "2 cameras"},
    ),
    dict(
        slug="lumen-smart-led-bulbs-4-pack",
        store="apex",
        brand="Lumen",
        cat="smart-home",
        title="Lumen Smart LED Bulbs, Tunable White, 4-Pack",
        price=34.99,
        list=None,
        rating=4.5,
        count=15400,
        bought=2100,
        stock=300,
        badges=[],
        speed="one_day",
        images=2,
        desc="Dimmable smart bulbs from warm to daylight white, no hub required.",
        hl=["2700K to 6500K tunable white", "No hub required", "Schedules and scenes in the app"],
        specs={"Brightness": "800 lumens (60W equivalent)", "Base": "E26", "Pack": "4 bulbs"},
    ),
    dict(
        slug="orbit-video-doorbell-2k",
        store="apex",
        brand="Orbit",
        cat="smart-home",
        title="Orbit 2K Video Doorbell with Head-to-Toe View",
        price=99.99,
        list=129.99,
        rating=4.3,
        count=5400,
        bought=620,
        stock=55,
        badges=[],
        speed="two_day",
        images=2,
        desc="See who's at the door, head to toe, and talk to them from anywhere.",
        hl=["2K HDR head-to-toe video", "Package detection", "Battery or wired power"],
        specs={"Resolution": "2K HDR", "Power": "Battery or wired", "Field of view": "150 degrees"},
    ),
    dict(
        slug="nestly-4k-streaming-stick",
        store="apex",
        brand="Nestly",
        cat="smart-home",
        title="Nestly 4K Streaming Stick with Voice Remote",
        price=39.99,
        list=49.99,
        rating=4.6,
        count=33200,
        bought=4100,
        stock=260,
        badges=["Best Seller"],
        speed="one_day",
        images=2,
        desc="Stream in 4K HDR with Dolby Vision and a voice remote that also controls your TV.",
        hl=["4K HDR, Dolby Vision and Atmos", "Voice remote with TV controls", "Wi-Fi 6 support"],
        specs={"Video": "4K HDR, Dolby Vision", "Audio": "Dolby Atmos", "Connectivity": "Wi-Fi 6"},
    ),
    dict(
        slug="halcyon-smart-hepa-air-purifier",
        store="apex",
        brand="Halcyon",
        cat="smart-home",
        title="Halcyon Smart HEPA Air Purifier for Large Rooms",
        price=149.00,
        list=179.00,
        rating=4.6,
        count=3900,
        bought=430,
        stock=40,
        badges=[],
        speed="two_day",
        images=2,
        desc="True HEPA filtration for rooms up to 1,000 sq ft, with a live air-quality ring.",
        hl=["True HEPA H13 filter", "Covers up to 1,000 sq ft", "Whisper-quiet sleep mode, 24dB"],
        specs={"Coverage": "1,000 sq ft", "Filter": "H13 True HEPA", "Noise": "24 dB (sleep)"},
    ),
    # ---------------------------------------------------------------- kitchen
    dict(
        slug="brewline-baristapro-conical-burr-grinder",
        store="apex",
        brand="Brewline",
        cat="kitchen",
        title="Brewline BaristaPro Conical Burr Precision Electric Coffee Grinder",
        price=89.99,
        list=124.99,
        rating=4.6,
        count=5120,
        bought=780,
        stock=44,
        badges=["Limited Deal"],
        speed="one_day",
        images=2,
        deal=(28, 7, 150, 81),
        desc="40 grind settings from espresso to cold brew, with stainless conical burrs and a timer.",
        hl=["40mm stainless conical burrs", "40 grind settings", "Precision timer in 0.2s steps"],
        specs={"Burrs": "40mm conical, stainless", "Settings": "40", "Hopper": "350 g"},
    ),
    dict(
        slug="brewline-espresso-machine-15-bar",
        store="apex",
        brand="Brewline",
        cat="kitchen",
        title="Brewline Studio 15-Bar Espresso Machine with Steam Wand",
        price=199.00,
        list=249.00,
        rating=4.5,
        count=2400,
        bought=260,
        stock=22,
        badges=["Apex Choice"],
        speed="two_day",
        images=2,
        desc="Cafe-style espresso and silky milk at home, with a 58mm portafilter and PID temperature control.",
        hl=["15-bar pump with PID control", "Commercial-style 58mm portafilter", "Powerful steam wand"],
        specs={"Pressure": "15 bar", "Portafilter": "58 mm", "Water tank": "1.8 L"},
    ),
    dict(
        slug="brewline-electric-gooseneck-kettle",
        store="apex",
        brand="Brewline",
        cat="kitchen",
        title="Brewline Electric Gooseneck Kettle with Temperature Control",
        price=59.99,
        list=None,
        rating=4.7,
        count=6900,
        bought=650,
        stock=70,
        badges=["Top Rated"],
        speed="one_day",
        images=2,
        desc="Precise pour-over control with a hold-temperature mode and a built-in brew timer.",
        hl=[
            "Set any temperature from 135 to 212F",
            "Hold mode keeps water hot for 60 minutes",
            "Counterbalanced handle",
        ],
        specs={"Capacity": "0.9 L", "Power": "1200 W", "Material": "Stainless steel"},
    ),
    dict(
        slug="halcyon-compact-toaster-oven",
        store="apex",
        brand="Halcyon",
        cat="kitchen",
        title="Halcyon Compact Retro Toaster Oven, 4-Slice",
        price=79.99,
        list=99.99,
        rating=4.4,
        count=1780,
        bought=210,
        stock=35,
        badges=["New Arrival"],
        speed="two_day",
        images=2,
        desc="A retro countertop oven that toasts, bakes and broils, in three soft colors.",
        hl=["Toast, bake, broil and keep warm", "Fits a 9-inch pizza", "60-minute timer"],
        specs={"Capacity": "4 slices", "Power": "1100 W"},
        colors=[("Blush Pink", "#e8b4b8", 0, 12), ("Stone", "#d6d3d1", 0, 15), ("Cream", "#f5efe0", 0, 8)],
    ),
    # ------------------------------------------------------------ accessories
    dict(
        slug="voltix-powercore-mag-20000-battery",
        store="apex",
        brand="Voltix",
        cat="accessories",
        title="Voltix PowerCore Mag 20,000mAh Ultra-Slim Magnetic Battery Bank",
        price=45.49,
        list=69.99,
        rating=4.5,
        count=4300,
        bought=1100,
        stock=120,
        badges=["Limited Deal"],
        speed="one_day",
        images=2,
        deal=(35, 4, 180, 148),
        desc="A slim aluminum power bank that charges a phone four times, with 30W USB-C fast charging.",
        hl=["20,000mAh, about four phone charges", "30W USB-C power delivery", "Charges two devices at once"],
        specs={"Capacity": "20,000 mAh", "Output": "30 W USB-C PD", "Weight": "350 g"},
    ),
    dict(
        slug="voltix-65w-gan-charger",
        store="apex",
        brand="Voltix",
        cat="accessories",
        title="Voltix 65W GaN Dual USB-C Fast Charger",
        price=39.99,
        list=49.99,
        rating=4.7,
        count=9100,
        bought=1850,
        stock=230,
        badges=["Best Seller"],
        speed="one_day",
        images=2,
        desc="Charge a laptop and a phone at once from a charger the size of a phone brick.",
        hl=["65W total output", "Two USB-C ports", "Gallium nitride: small and cool"],
        specs={"Output": "65 W", "Ports": "2 x USB-C", "Size": "40 x 40 x 32 mm"},
    ),
    dict(
        slug="apex-ultrahub-7-in-1-usb-c-adapter",
        store="apex",
        brand="Apex",
        cat="accessories",
        title="Apex UltraHub 7-in-1 USB-C Laptop Docking Adapter, 4K HDMI",
        price=49.99,
        list=59.99,
        rating=4.5,
        count=3800,
        bought=720,
        stock=150,
        badges=[],
        speed="one_day",
        images=2,
        desc="Add HDMI, USB-A, SD and pass-through charging to any USB-C laptop.",
        hl=["4K 60Hz HDMI", "100W pass-through charging", "SD and microSD readers"],
        specs={"Ports": "HDMI, 2x USB-A, USB-C PD, SD, microSD, Ethernet", "HDMI": "4K 60Hz"},
    ),
    dict(
        slug="apex-studio-desk-mat-xl",
        store="apex",
        brand="Apex",
        cat="accessories",
        title="Apex Studio Ergonomic Desk Mat XL, Dual-Sided",
        price=24.99,
        list=None,
        rating=4.6,
        count=5100,
        bought=900,
        stock=210,
        badges=[],
        speed="one_day",
        images=2,
        desc="A large, water-resistant desk mat with a soft felt side and a smooth vegan leather side.",
        hl=["90 x 40 cm", "Felt on one side, vegan leather on the other", "Non-slip base"],
        specs={"Size": "90 x 40 cm", "Material": "Vegan leather and felt"},
    ),
    dict(
        slug="halcyon-ergonomic-office-chair",
        store="apex",
        brand="Halcyon",
        cat="accessories",
        title="Halcyon Ergonomic Mesh Office Chair with Adjustable Lumbar",
        price=289.00,
        list=349.00,
        rating=4.5,
        count=2600,
        bought=240,
        stock=26,
        featured=True,
        badges=[],
        speed="standard",
        images=2,
        desc="Breathable mesh, adjustable lumbar support and 4D armrests for long workdays.",
        hl=["Adjustable lumbar and headrest", "4D armrests", "Holds up to 300 lb"],
        specs={"Material": "Mesh", "Max load": "300 lb", "Armrests": "4D adjustable"},
    ),
    dict(
        slug="apex-dual-monitor-arm",
        store="apex",
        brand="Apex",
        cat="accessories",
        title='Apex Dual Monitor Arm, Gas Spring, for 17-32" Screens',
        price=79.99,
        list=99.99,
        rating=4.6,
        count=3300,
        bought=310,
        stock=5,
        badges=[],
        speed="two_day",
        images=2,
        desc="Float two monitors over your desk and move them with one hand.",
        hl=["Gas spring arms", "Fits 17 to 32-inch monitors", "Clamp or grommet mount"],
        specs={"Screen size": "17 to 32 in", "Load": "2 to 9 kg per arm", "Mount": "VESA 75/100"},
    ),
    dict(
        slug="voltix-braided-usb-c-cable-2-pack",
        store="apex",
        brand="Voltix",
        cat="accessories",
        title="Voltix Braided USB-C to USB-C Cable, 100W, 6ft (2-Pack)",
        price=14.99,
        list=19.99,
        rating=4.7,
        count=14100,
        bought=3300,
        stock=500,
        badges=[],
        speed="one_day",
        images=2,
        desc="Tough braided cables rated for 100W charging and 10,000+ bends.",
        hl=["100W charging", "Braided nylon, 10,000+ bends", "Two 6 ft cables"],
        specs={"Length": "6 ft", "Power": "100 W", "Pack": "2 cables"},
    ),
    dict(
        slug="northwind-hard-shell-headphone-case",
        store="northwind",
        brand="Northwind",
        cat="accessories",
        title="Northwind Hard Shell Travel Case for Over-Ear Headphones",
        price=29.99,
        list=None,
        rating=4.8,
        count=892,
        bought=410,
        stock=95,
        badges=[],
        speed="one_day",
        images=2,
        desc="A crush-resistant zip case with a pocket for cables and a flight adapter.",
        hl=["Crush-resistant EVA shell", "Mesh pocket for cables", "Fits most over-ear headphones"],
        specs={"Material": "EVA hard shell", "Fits": "Most over-ear headphones"},
    ),
    dict(
        slug="apex-solid-metal-headphone-stand",
        store="apex",
        brand="Apex",
        cat="accessories",
        title="Apex Solid Metal Headphone Stand",
        price=14.99,
        list=None,
        rating=4.7,
        count=2400,
        bought=530,
        stock=140,
        badges=[],
        speed="one_day",
        images=2,
        desc="A weighted aluminum stand that keeps your headphones off the desk and in shape.",
        hl=["Weighted aluminum base", "Silicone padding protects the headband", "Fits all headphone sizes"],
        specs={"Material": "Aluminum", "Height": "27 cm"},
    ),
    dict(
        slug="keyforge-coiled-usb-c-keyboard-cable",
        store="keyforge",
        brand="KeyForge",
        cat="accessories",
        title="KeyForge Custom Coiled USB-C Keyboard Aviator Cable (1.5m)",
        price=18.50,
        list=22.00,
        rating=4.9,
        count=1420,
        bought=620,
        stock=180,
        badges=[],
        speed="one_day",
        images=2,
        desc="A coiled, double-sleeved cable with a detachable aviator connector, in pastel colors.",
        hl=["Detachable GX16 aviator connector", "Double-sleeved paracord", "1.5 m total length"],
        specs={"Length": "1.5 m", "Connector": "USB-C to USB-A"},
        colors=[("Pastel Blue", "#bfdbfe", 0, 90), ("Pastel Pink", "#fbcfe8", 0, 90)],
    ),
    dict(
        slug="keyforge-walnut-wrist-rest",
        store="keyforge",
        brand="KeyForge",
        cat="accessories",
        title="KeyForge Walnut Keyboard Wrist Rest, 75% / TKL",
        price=16.99,
        list=None,
        rating=4.6,
        count=678,
        bought=190,
        stock=5,
        badges=[],
        speed="two_day",
        images=2,
        desc="A solid walnut wrist rest with a non-slip base, sized for 75% and TKL boards.",
        hl=["Solid American walnut", "Non-slip rubber feet", "Sized for 75% and TKL keyboards"],
        specs={"Material": "Walnut", "Size": "36 x 8 cm"},
    ),
    # -------------------------------------------------------------- wearables
    dict(
        slug="apex-chrono-4-pro-smartwatch",
        store="apex",
        brand="Apex",
        cat="wearables",
        title="Apex Chrono 4 Pro Titanium Smartwatch with GPS",
        price=179.99,
        list=249.99,
        rating=4.8,
        count=12450,
        bought=1900,
        stock=150,
        badges=["Limited Deal"],
        speed="one_day",
        images=2,
        deal=(28, 8, 500, 340),
        desc="A titanium smartwatch with dual-band GPS, a bright always-on display and 7-day battery life.",
        hl=["Titanium case, sapphire glass", "Dual-band GPS", "7 days of battery life"],
        specs={"Display": '1.9" AMOLED, always-on', "Water resistance": "5 ATM", "Battery": "Up to 7 days"},
        colors=[("Sage", "#c9d6c3", 0, 80), ("Graphite", BLACK, 0, 70)],
    ),
    # ------------------------------------------------------------------ drafts
    dict(
        slug="keyforge-horizon-65-aluminum-edition",
        store="keyforge",
        brand="KeyForge",
        cat="keyboards",
        title="KeyForge Horizon 65 Aluminum Edition (Pre-order)",
        status="draft",
        price=169.99,
        list=None,
        rating=0,
        count=0,
        bought=0,
        stock=0,
        badges=["New Arrival"],
        speed="standard",
        images=1,
        image_from="keyforge-horizon-75-tri-mode-keyboard-3",
        desc="Our next board: a 65% layout in a full CNC aluminum case.",
        hl=[],
        specs={},
    ),
    dict(
        slug="keyforge-artisan-keycap-set",
        store="keyforge",
        brand="KeyForge",
        cat="accessories",
        title="KeyForge Artisan Retro Keycap Set, 128 Keys",
        status="draft",
        price=44.99,
        list=None,
        rating=0,
        count=0,
        bought=0,
        stock=25,
        badges=[],
        speed="standard",
        images=1,
        image_from="keyforge-retro-97-smart-display-keyboard-2",
        desc="Round, retro-style PBT keycaps for most layouts.",
        hl=[],
        specs={},
    ),
    dict(
        slug="northwind-studio-50-wireless",
        store="northwind",
        brand="Northwind",
        cat="audio",
        title="Northwind Studio 50 Wireless (Coming Soon)",
        status="draft",
        price=159.99,
        list=None,
        rating=0,
        count=0,
        bought=0,
        stock=0,
        badges=[],
        speed="standard",
        images=1,
        image_from="northwind-studio-50-reference-headphones-3",
        desc="The Studio 50 sound, now wireless.",
        hl=[],
        specs={},
    ),
    dict(
        slug="apex-zenith-ultra-16-laptop",
        store="apex",
        brand="Apex",
        cat="laptops",
        title="Apex Zenith Ultra 16 Laptop (Draft listing)",
        status="draft",
        price=1499.00,
        list=None,
        rating=0,
        count=0,
        bought=0,
        stock=0,
        badges=[],
        speed="standard",
        images=1,
        image_from="apex-zenith-ultra-14-laptop-3",
        desc="Bigger screen, same all-day battery.",
        hl=[],
        specs={},
    ),
]

REVIEWERS = [
    "Marcus Vance",
    "Elena Rostova",
    "Priya Natarajan",
    "Daniel Okafor",
    "Sofia Martins",
    "Liam O'Connell",
    "Hannah Kim",
    "Mateo Alvarez",
    "Grace Thompson",
    "Yuki Tanaka",
    "Omar Haddad",
    "Chloe Dubois",
    "Noah Fischer",
    "Aisha Bello",
    "Ethan Brooks",
    "Isabella Rossi",
]

REVIEWS = {
    "audio": [
        (
            5,
            "Finally beats the category leader in battery and spatial stage",
            "I fly transpacific routes twice a month. The adaptive ANC completely removed the low cabin hum on a "
            "14-hour flight and the battery still showed plenty left on arrival. Ear cups don't pinch my glasses.",
        ),
        (
            5,
            "Audio mixing clarity and seamless multipoint switching",
            "Switching between my laptop and phone is instant. Calls sound clear on both ends and the bass is "
            "tight without muddying vocals.",
        ),
        (
            4,
            "Great sound, case could be smaller",
            "Sound and noise cancelling are excellent for the price. The case is a little bulky for my bag, which "
            "is the only reason for four stars.",
        ),
        (
            5,
            "Comfortable for a full workday",
            "I wear these 8+ hours a day for work calls and music. No hot spots, no headache, and the battery "
            "lasts the whole week.",
        ),
        (
            3,
            "Good, but the app needs work",
            "Hardware is solid and the sound is pleasant. The companion app disconnects sometimes and the EQ "
            "presets are limited.",
        ),
        (
            4,
            "Clear, balanced and easy to pair",
            "Paired in seconds. Highs are crisp, mids are clear. I'd like a little more bass, but the EQ helps.",
        ),
        (
            2,
            "Mine developed a crackle",
            "Worked well for two weeks and then the left side started crackling. Support replaced it quickly, "
            "the new one is fine so far.",
        ),
    ],
    "keyboards": [
        (
            5,
            "The best typing feel I've had under $150",
            "The gasket mount makes typing soft and quiet, and the pre-lubed switches are smooth out of the box. "
            "Wireless has had zero lag for gaming.",
        ),
        (
            5,
            "Sounds amazing, stays connected",
            "Thocky sound with no rattle on the stabilizers. Switching between my Mac and PC is one key combo.",
        ),
        (
            4,
            "Great board, software is basic",
            "Build quality is excellent and the hot-swap sockets made it easy to try other switches. The "
            "remapping software is basic but works.",
        ),
        (
            5,
            "Perfect size for a small desk",
            "I wanted arrows without a numpad and this is exactly that. The battery lasts weeks with lights off.",
        ),
        (
            3,
            "Nice keyboard, keycaps shine quickly",
            "Typing feel is good but the legends started to shine after a month of heavy use.",
        ),
        (
            4,
            "Satisfying to type on",
            "I write all day and my hands feel less tired than on my old laptop keyboard.",
        ),
    ],
    "general": [
        (
            5,
            "Exactly as described",
            "Arrived the next day, well packaged, and works perfectly. Setup took less than five minutes.",
        ),
        (
            4,
            "Very good value",
            "Does everything I need at a fair price. Build quality feels better than expected.",
        ),
        (
            5,
            "Would buy again",
            "This replaced a more expensive model I owned and honestly works better. Highly recommended.",
        ),
        (
            3,
            "Fine, a few small issues",
            "It works, but the instructions were unclear and I had to look up a video to finish setup.",
        ),
        (
            5,
            "Looks great on my desk",
            "Clean design that fits with the rest of my setup. Solid and well made.",
        ),
        (4, "Happy with it", "Reliable so far after two months of daily use. Only minor nitpicks."),
        (
            1,
            "Arrived damaged",
            "The box was crushed and the item had a cracked corner. The return was easy at least.",
        ),
    ],
}

PROMO_CODES = [
    ("APEX10", 10, True, 365),
    ("WELCOME15", 15, True, 365),
    ("SAVE20", 20, True, 90),
    ("SUMMER5", 5, False, -10),
]
